# $OpenBSD$

COMMENT=	minimalist password safe

DISTNAME=	mdp-1.0
CATEGORIES=	security

MAINTAINER=	Bertrand Janin <b@grun.gy>

# BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	http://tamentis.com/projects/mdp/files/

WANTLIB= 	c

NO_REGRESS=	Yes

.include <bsd.port.mk>

