all: src/${PROG}

src/${PROG}:
	cd src/ && make

install: src/${PROG}
	install -d -m 755 ${PREFIX}/bin
	install -m 755 src/${PROG} ${PREFIX}/bin
	install -d -m 755 ${PREFIX}/${MANDEST}/man1
	install -m 644 ${PROG}.1 ${PREFIX}/${MANDEST}/man1

mantest:
	nroff -man ${PROG}.1 | less -R

clean:
	cd src/ && make clean

test:
	sh test.sh

README: ${PROG}.1
	nroff -c -man ${PROG}.1 | col -b > README
