.\"
.\" Copyright (c) 2012-2014 Bertrand Janin <b@janin.com>
.\" 
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: July 15 2013 $
.Dt MDP 1
.Os
.Sh NAME
.Nm mdp
.Nd minimalist password safe
.Sh SYNOPSIS
.Nm mdp
.Bk -words
.Fl e
.Op Fl Vh
.Op Fl c Ar config
.Op Fl k Ar key_id
.Ek
.Nm mdp
.Fl g
.Bk -words
.Op Fl Vh
.Op Fl c Ar config
.Op Fl p Ar profile
.Op Fl n Ar count
.Op Fl l Ar length
.Ek
.Nm mdp
.Bk -words
.Op Fl ErqVh
.Op Fl c Ar config
.Ar keyword ...
.Ek
.Sh DESCRIPTION
.Nm
wraps GnuPG, your favorite editor, a password generator and a custom temporary
full-screen pager to let you manage your password library.
.Pp
Naturally edit your password file (create, sort, delete) with your editor, rely
on GnuPG to do the right thing for crypto and let
.Nm
do the rest. In order to avoid passwords to linger on your screen, results
from your queries are displayed through a custom pager that gets cleared after
a customizable timeout (default 10 seconds).
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar config
Use an alternate configuration file.
.It Fl e
Edit your password file (decrypt and re-encrypt after the fact).
.It Fl g
Generate password(s) according to your configuration or command-line arguments.
.It Fl E
Use regexes instead of plain text matches (e.g. ^.mail).
.It Fl k Ar key_id
GnuPG key id (8 alpha-numeric characters). This could be used to specify your
GnuPG key id in case you did not define it in your configuration file.
.It Fl p Ar profile
Choose which profile to use among the ones defined in your configuration file.
.It Fl n Ar count
Number of passwords to generate. This command line parameter will override all
other values of password_count (global and profile).
.It Fl l Ar length
Length of generated passwords (in bytes). This command line parameter will
override all other values of password_count (global and profile).
.It Fl q
Start
.Nm
in query mode instead of displaying results directly. This will avoid you
from entering your GPG password multiple time. Query mode times out after
a few seconds of inactivity.
.It Fl r
Displays the result without pager, plain terminal dump (not recommended).
.It Fl V
Print version.
.It Fl h
Print usage.
.El
.Sh USAGE
.Bl -tag -width Ds
.It 1. Create your GPG key if you don't already have one.
.It 2. Setup your EDITOR variable if it's not already done.
.It 3. Create a .mdp/config file from the example (at least gpg_key_id).
.It 4. Pick a password from randomly generated ones, for example:
.Bd -literal -offset indent
mdp -g
.Ed
.It 5. Run "mdp -e" and add a line such as:
.Bd -literal -offset indent
twitter sponge@bob.com yHVHPnqXyx6qUuki
.Ed
.It 6. Now when you need your Twitter password, you can just type:
.Bd -literal -offset indent
mdp twitter
.Ed
.El
.Sh CONFIGURATION
This is a summary of all the available configuration variables and options:
.Bl -tag -width Ds
.It Xo Ic set gpg_path Ar path
.Xc
GnuPG absolute path (default: /usr/bin/gpg)
.Pp
.It Ic set gpg_key_id Ar key_id
GnuPG key id (default: none). If no key is selected,
.Nm
will expect you to specify it on the command-line (-k). If no key was specified
either way,
.Nm
will abort. That this parameter is ignored during the decryption phase, GnuPG
picks the key based on the content of the password file.
.Pp
.It Ic set gpg_timeout Ar seconds
Number of seconds to give GnuPG for password and pipe interaction. The
default value is 10 seconds. This will kill GnuPG if forgotten at the password
prompt or if it cannot communicate with the parent process.
.Pp
.It Ic set editor Ar path
Path to your favorite editor. You typically don't need to set this variable
since
.Nm
will use your default editor (as defined by $EDITOR). If
.Nm
detects vim, it will attempt to add the -n parameter to avoid vim from creating
swap files.
.Pp
.It Ic set password_count Ar count
Define how many password to show with using -g. Default: 4 or as defined in the
profile.
.Pp
.It Ic set character_count Ar count
Define how many characters to randomize per password. Default: 16 or as defined
in the profile.
.Pp
.It Ic set character_set Ar characters
Define all the characters to use in your passwords. Default: all alphanumeric
(upper and lower case) or as define in the profile. The following aliases are
supported as shortcuts: $LOWERCASE, $UPPERCASE, $ALPHA, $DIGITS, $ALPHANUMERIC,
$SYMBOLS, $PRINTABLE.
.Pp
.It Ic set backup Ar no
Define whether we keep a backup every time we edit the password file. Default:
yes.
.Pp
.It Ic set timeout Ar seconds
This variable define how long the pager will display your passwords. The
default value is 10 seconds.
.Nm
will use your default editor (as defined by $EDITOR). 
.It Ic profile Ar name
All the variables define below a profile header will be specific to this
profile. For now only password_count, character_count and character_set are
valid options.
.El
.Sh PASSWORD FILE
Your password file should be structured to make it convenient for mdp to query
it. Since mdp queries work similarly to grep, you want to use a line-based
system with one line per password. The simplest line format is:
.Bd -literal -offset indent
nameOfServiceA   password1
anotherService   password2
.Ed
.Pp
You can separate your name/notes and your password with spaces, tabs or any
character except new-line (\\n). This format allows you to find the services by name, e.g.:
.Bd -literal -offset indent
mdp serviceA
.Ed
.Pp
You can use any number of namespacing hints if you need more structure, the
following allow you to fetch all your email passwords at once:
.Bd -literal -offset indent
email     serviceA       password1
email     serviceB       password2
irc       serviceC       password3
.Ed
.Pp
You can use '#' in the beginning of a line to avoid mdp from displaying a
password. This is particularly useful to add meta data to your password file or
keep track of previous password without adding noise to the output. For example:
.Bd -literal -offset indent
# email services
serviceA     password1
serviceB     password2

# irc servers
serviceC     password3
.Ed
.Pp
Empty lines are naturally ignored.
.Sh FAQ
.Bl -tag -width Ds
.It Why not 'shred' the temporary file?
If you are afraid of getting your disk stolen, encrypt it. Shred has limited
use on most journaled file-systems.
.It What if I don't trust 'root'?
You're screwed, you can't trust this machine with your valuable information.
.It What if my server is virtualized?
Same answer as above, if you don't trust your hosting provider or IaaS, good
luck.
.El
.Sh ENVIRONMENT
.Bl -tag
.It Ev EDITOR
The content of this variable will be used as default editor if the
configuration does not alter it.
.El
.Sh FILES
.Bl -tag
.It Pa $HOME/.mdp/config
Main configuration file for
.Nm .
You need at least your gpg_key_id in there, without it you will be required to
specify it every single time.
.It Pa $HOME/.mdp/passwords
Encrypted list of passwords.
.It Pa $HOME/.mdp/passwords.bak
This file is a copy of your password file, before the last edit. You can revert
to the last file by simply replacing your password file. Creation of this file
can be disabled (see "set backup").
.It Pa $HOME/.mdp/lock
This file is created while you edit your password list to avoid two copies
of mdp to run at the same time for the same user.
.El
.Sh SEE ALSO
.Xr gpg 1 ,
.Xr sh 1
.Sh BUGS
.Bl -tag -width Ds
.It - None that we know of.
.El
.Sh AUTHORS
mdp was written by Bertrand Janin <b@janin.com> and is distributed under an ISC
license (BSD, MIT and OSI compatible).
.Pp
A bunch of utility functions are borrowed from OpenBSD and OpenSSH, both
under ISC and BSD licenses, with copyrights from the following authors:
.Pp
    Copyright (c) 2004 Ted Unangst and Todd Miller
    Copyright (c) 1998 Todd C. Miller <Todd.Miller@courtesan.com>
    Copyright (c) 2000 Markus Friedl.  All rights reserved.
    Copyright (c) 2005,2006 Damien Miller.  All rights reserved.
.Pp
The random password generator was mostly borrowed from apg (also BSD
licensed), with the following copyright notice:
.Pp
    Copyright (c) 1999, 2000, 2001, 2002, 2003
    Adel I. Mirzazhanov. All rights reserved
.Pp
The array and xmalloc libraries are taken from tmux, with the following
copyright notices:
.Pp
    Copyright (c) 2004 Nicholas Marriott <nicm@users.sourceforge.net>
    Copyright (c) 2006 Nicholas Marriott <nicm@users.sourceforge.net>
