.\"
.\" Copyright (c) 2012 Bertrand Janin <b@grun.gy>
.\" 
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: July 22 2012 $
.Dt MDP 1
.Os
.Sh NAME
.Nm mdp
.Nd minimalist password safe
.Sh SYNOPSIS
.Nm mdp
.Bk -words
.Op Fl c Ar config
.Op Fl er
.Op Ar keyword ...
.Ek
.Sh DESCRIPTION
.Nm
is an acronym for "Mot de Passe", meaning "password" in French. It wraps GnuPG
for encryption and deals with all the small details of generating, managing and
fetching your passwords.
.Pp
.Nm
is similar to a dozen other programs. What differentiate it from others is an
overall goal for simplicity, not your average button-driven simplicity but more
like a Unix-y less is more style. For example, beyond the use of GnuPG for
encryption,
.Nm
lets you use your own editor to manage your passwords, categorize them and
delete them. I wouldn't use anything but my favorite editor to manage a list,
would you?
.Pp
In order to avoid passwords to linger on your screen, the results from the
queries are displayed through a custom pager that gets cleared after a
customizable timeout (default 10 seconds).
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar config
Use an alternate configuration file.
.It Fl e
Edit your password file (decrypt and re-encrypt after the fact).
.It Fl r
Displays the result without pager, plain terminal dump.
.It Fl g Ar length
Generates 4 passwords of the given length.
.El
.Sh SEE ALSO
.Xr gpg 1 ,
.Xr sh 1
.Sh BUGS
None so far.
.Sh AUTHORS
mdp was written by Bertrand Janin <b@grun.gy> and is distributed under an ISC
license (BSD compatible, OSI compatible).

A bunch of utility functions are borrowed from OpenBSD and OpenSSH, both
under ISC and BSD licenses, with copyrights from the following authors:

    Copyright (c) 2004 Ted Unangst and Todd Miller
    Copyright (c) 1998 Todd C. Miller <Todd.Miller@courtesan.com>
    Copyright (c) 2000 Markus Friedl.  All rights reserved.
    Copyright (c) 2005,2006 Damien Miller.  All rights reserved.

