PROG=stub
SRC=../../../src
OBJECTS= \
	stub.o \
	${SRC}/debug.o \
	${SRC}/lock.o \
	${SRC}/utils.o \
	${SRC}/xmalloc.o

OBJECTS+=${EXTRA_OBJECTS}
CFLAGS+=-I${SRC}/

all: ${PROG}

arc4random.o:
	cp ${SRC}/arc4random.o .

strlcpy.o:
	cp ${SRC}/strlcpy.o .

wcslcpy.o:
	cp ${SRC}/wcslcpy.o .

${PROG}: ${OBJECTS}
	${CC} ${LDFLAGS} -o ${PROG} ${OBJECTS} ${CURSESLIB} 

test: ${PROG}
	./test_lock_exists.sh
	./test_lock_set.sh
	./test_lock_unset.sh

clean:
	rm -f ${PROG} *.o *core expected output diff
