PROG=stub
OBJECTS= \
	stub.o \
	../../../src/debug.o \
	../../../src/lock.o \
	../../../src/utils.o \
	../../../src/xmalloc.o

OBJECTS+=${EXTRA_OBJECTS}
CFLAGS+=-I../../../src/

all: ${PROG}

${PROG}: ${OBJECTS}
	${CC} ${LDFLAGS} -o ${PROG} ${OBJECTS} ${CURSESLIB} 

test: ${PROG}
	./test_lock_exists.sh
	./test_lock_set.sh
	./test_lock_unset.sh

clean:
	rm -f ${PROG} *.o *core expected output diff
