PROG=stub
OBJECTS= \
	stub.o \
	../../../src/generate.o \
	../../../src/randpass.o

OBJECTS+=${EXTRA_OBJECTS}
CFLAGS+=-I../../../src/

all: ${PROG}

${PROG}: ${OBJECTS}
	${CC} ${LDFLAGS} -o ${PROG} ${OBJECTS} ${CURSESLIB} 

test: ${PROG}
	./test_generate_passwords.sh

clean:
	rm -f ${PROG} *.o *core expected output diff
