PROG=stub
SRC=../../../src
OBJECTS= \
	stub.o \
	${SRC}/generate.o \
	${SRC}/randpass.o

OBJECTS+=${EXTRA_OBJECTS}
CFLAGS+=-I${SRC}/

all: ${PROG}

arc4random.o:
	cp ${SRC}/arc4random.o .

strlcpy.o:
	cp ${SRC}/strlcpy.o .

wcslcpy.o:
	cp ${SRC}/wcslcpy.o .

${PROG}: ${OBJECTS}
	${CC} ${LDFLAGS} -o ${PROG} ${OBJECTS} ${CURSESLIB} 

test: ${PROG}
	./test_generate_passwords.sh

clean:
	rm -f ${PROG} *.o *core expected output diff
