OBJECTS= \
	cleanup.o \
	cmd.o \
	config.o \
	curses.o \
	debug.o \
	editor.o \
	generate.o \
	gpg.o \
	keywords.o \
	lock.o \
	main.o \
	pager.o \
	randpass.o \
	results.o \
	strdelim.o \
	utils.o \
	xmalloc.o

OBJECTS+=${EXTRA_OBJECTS}

all: ${PROG}

${PROG}: ${OBJECTS}
	${CC} ${LDFLAGS} -o ${PROG} ${OBJECTS} ${CURSESLIB} 

clean:
	rm -f ${PROG} ${OBJECTS} test.o *core
